-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.foods
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    value text COLLATE pg_catalog."default",
    CONSTRAINT foods_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.foods
    OWNER to postgres;

GRANT ALL ON TABLE public.foods TO anon;

GRANT ALL ON TABLE public.foods TO authenticated;

GRANT ALL ON TABLE public.foods TO postgres;

GRANT ALL ON TABLE public.foods TO service_role;
